### ISSUE TITLE
fitexpr example not working

### ISSUE THREAD

**Issue by rcnlee** [abeschneider/GrammaticalEvolution#1]
Hello,
The fitexpr example seems to be broken in the current version.

``` julia
julia> include("fitexpr.jl")
generation: 1, max fitness=-1.0, code=nothing
```

The problem seems to be that ind.fitness=-1.0 is used as an invalid flag.  However, the check is assuming 'nothing' as a flag.

``` julia
if getFitness(pop[i]) == nothing
    evaluate!(grammar, pop[i], args...)
end
```

which leads to evaluate! not being called on the individuals.
Thanks!

**Comment by abeschneider** [comment]
I'll take a look. I haven't had time to properly maintain this library, and there was a code refactoring in place that didn't get finished. I can either roll-back to the previous working version or see if it's viable to finish the re-factor.

**Comment by rcnlee** [comment]
Thanks @abeschneider.  I'd like to try out the package for my project soon (probably starting tomorrow).  If there is something quick that you can do, that would be great.  Perhaps rolling it back to a working version and moving the refactoring to a dev branch.  I can also contribute if you can point me in the right direction. Thanks!

**Comment by abeschneider** [comment]
Okay, several items:
1. Apparently I never pushed the refactored code, which is probably good because it wasn't it working condition (possibly bad in that the code might be lost forever).
2. There were a ton of warnings due to Julia 0.4 which are now fixed
3. The bug you experienced was due, as you suggested, to (somehow) the fitness getting checked against `nothing` while its value was set to `-1.0`. This was fixed.

Please let me know if you run into any other problems, and also all contributions are very welcome. Unfortunately, I haven't had time to give this library the updates it needs. That said, I think Julia is the perfect language for something like GE.

Some things that could definitely use some inspection:
1. There is potentially an issue with the `or` rule. I know I had to fix something similar in PEGParser
2. Some of the macro expansion can be made better, again by looking at PEGParser
