### ISSUE TITLE
OrRule leads to MaxWrapExceptions

### ISSUE THREAD

**Issue by rcnlee** [abeschneider/GrammaticalEvolution#2]
I'll take a deeper look at PEGParser tomorrow to see if I can find a solution as @abeschneider suggested earlier, but I'd just like to document the issue here and see if I can get any feedback.
Here is my grammar and surrounding code to reproduce.

``` julia
using GrammaticalEvolution
include("ExamplePopulation.jl")
convert_number(lst) = float(join(lst))
function create_grammar()
  @grammar grammar begin
    start = bin

    bin = and | or | not | lte | bin_feat | always | eventually
    and = Expr(:&&, bin, bin)
    or = Expr(:||, bin, bin)
    not = Expr(:call, :!, bin)
    lte = Expr(:call, :<=, real_feat, real_number) | Expr(:call, :<=, real_feat, real_feat) | Expr(:call, :<=, real_number, real_feat)
    bin_feat = Expr(:call, :get_feat, bin_feat_id, t)
    always = Expr(:call, :all, bin_vec) #globally
    eventually = Expr(:call, :any, bin_vec) #eventually

    bin_vec = vec_and | vec_or | vec_not | vec_lte
    vec_and = Expr(:call, :&, bin_vec, bin_vec)
    vec_or = Expr(:call, :|, bin_vec, bin_vec)
    vec_not = Expr(:call, :!, bin_vec)
    vec_lte = Expr(:call, :.<=, real_feat_vec, real_number) | Expr(:call, :.<=, real_feat_vec, real_feat_vec) | Expr(:call, :<=, real_number, real_feat_vec)

    real_feat = Expr(:call, :get_feat, real_feat_id, t)
    bin_feat = Expr(:call, :get_feat, bin_feat_id, t)
    real_feat_vec = Expr(:call, :get_feat, real_feat_id)
    bin_feat_vec = Expr(:call, :get_feat, bin_feat_id)

    real_feat_id = 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 22 | 26 | 27 | 28 | 29 | 33 | 34 | 35 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 57 | 61 | 62 | 63 | 64 | 68 | 69 | 70
    bin_feat_id = 1 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 23 | 24 | 25 | 30 | 31 | 32 | 36 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 | 65 | 66 | 67

    real_number[convert_number] = digit + '.' + digit
    digit = 0:9
    t = 1:50
  end

  return grammar
end
grammar = create_grammar()
pop = ExamplePopulation(10, 500)
code = transform(grammar, pop[1]) #if the first one doesn't fail, scroll through to others
```

This leads to a slew of MaxWrapExceptions originating from

``` julia
value = transform(grammar, rule.values[idx], ind, pos)
```

in

``` julia
function transform(grammar::Grammar, rule::OrRule, ind::Individual, pos::Task)
```

**Comment by abeschneider** [comment]
The `MaxWrapExceptions` occur during execution of `transform`. Because your genome is of limited size, during the transform, you can run out of codons. To deal with this, the algorithm wraps around to the beginning of codon. There is a a maximum allowed times that the algorithm is allowed, which can be controlled by the optional parameter `maxwraps` (which defaults to 2). While you can change maxwraps, there are two things to note:
1. You will likely always get this exception, as there will be individuals in your population that exercise some recursive part of your grammar. Thus, as shown in the examples, you should catch the exception in your loop. You can safely ignore it. It's there mostly for the ability to keep the statistics of the population.
2. Along with `maxwraps`, there is another parameter that controls the genome size (in `ExamplePopulation` it's the first parameter). The maximum genome size is actually a combination of the set genome size and `maxwraps`.

If you population doesn't seem to converge to the solution, it may be the maximum genome size is too small. You can play around with by either changing `maxwraps` and the genome size. To manually set `maxwraps`:

code = transform(grammar, pop[1], 5) # will set to maxwraps to 5

Increasing `maxwraps` and the genome size will increase your problem space, so will also likely slow the rate of convergence.

Hope this helps.

**Comment by rcnlee** [comment]
Thanks Abe!
